export const language = [
    { type: 'language', code: 'en', name: 'English', title: 'English' },
    { type: 'language', code: 'vi', name: 'Vietnamese', title: 'Tiếng Việt' },
    { type: 'language', code: 'ja', name: 'Japanese', title: '日本語' },
    { type: 'language', code: 'af', name: 'Afrikaans', title: 'Afrikaans' },
    { type: 'language', code: 'ak', name: 'Akan', title: 'Akan' },
    { type: 'language', code: 'sq', name: 'Albanian', title: 'Shqip' },
    { type: 'language', code: 'am', name: 'Amharic', title: 'አማርኛ' },
    { type: 'language', code: 'ar', name: 'Arabic', title: 'العربية' },
    { type: 'language', code: 'an', name: 'Aragonese', title: 'Aragonés' },
    { type: 'language', code: 'hy', name: 'Armenian', title: 'Հայերեն' },
    { type: 'language', code: 'as', name: 'Assamese', title: 'অসমীয়া' },
    { type: 'language', code: 'ae', name: 'Avestan', title: 'avesta' },
    { type: 'language', code: 'ay', name: 'Aymara', title: 'aymar aru' },
    {
        type: 'language',
        code: 'az',
        name: 'Azerbaijani',
        title: 'azərbaycan dili',
    },
    { type: 'language', code: 'bm', name: 'Bambara', title: 'bamanankan' },
    { type: 'language', code: 'ba', name: 'Bashkir', title: 'башҡорт теле' },
    { type: 'language', code: 'eu', name: 'Basque', title: 'euskara, euskera' },
    { type: 'language', code: 'be', name: 'Belarusian', title: 'Беларуская' },
    { type: 'language', code: 'bn', name: 'Bengali', title: 'বাংলা' },
    { type: 'language', code: 'bh', name: 'Bihari', title: 'भोजपुरी' },
    { type: 'language', code: 'bi', name: 'Bislama', title: 'Bislama' },
    { type: 'language', code: 'bs', name: 'Bosnian', title: 'bosanski jezik' },
    { type: 'language', code: 'br', name: 'Breton', title: 'brezhoneg' },
    {
        type: 'language',
        code: 'bg',
        name: 'Bulgarian',
        title: 'български език',
    },
    { type: 'language', code: 'my', name: 'Burmese', title: 'ဗမာစာ' },
    {
        type: 'language',
        code: 'ca',
        name: 'Catalan; Valencian',
        title: 'Català',
    },
    { type: 'language', code: 'ch', name: 'Chamorro', title: 'Chamoru' },
    { type: 'language', code: 'ce', name: 'Chechen', title: 'нохчийн мотт' },
]
